import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Tab } from "./lib/Tab";
import { Logo } from "./lib/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen p-6 flex flex-col items-center">
          <Logo />
          {children}
          <Tab />
        </div>
      </body>
    </html>
  );
}
